name: Deploy Infrastructure

on:
  workflow_call:
      inputs:
        environment:
          required: true
          description: "Environment to run the deploy on"
          type: string
        infrastructure_path:
          description: "Path of Infrastructure to deploy"
          type: string
          required: true
          default: "infrastructure"


concurrency: ${{github.repository}}-${{ inputs.environment }}-deployinfrastructure
jobs:
  deploy:
    name: Deploy ${{ inputs.environment }} -> ${{inputs.infrastructure_path}}
    runs-on: ubuntu-latest
    env:
      tf_version: '1.2.8'
      tg_version: 'v0.38.9'

    permissions:
      contents: read
      packages: write
      id-token: 'write'
    environment: ${{inputs.environment}}

    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Deploy
          uses: datadrivers/terragrunt-action@v0
          with:
            aws-role-to-assume: "idunno"
            terragrunt-working-directory: "./terragrunt"
            terraform-version: ${{ env.tf_version }}
            terragrunt-version: ${{ env.tg_version }}
            use-gcloud-auth: "true"
            gcp-workload-identity-provider:  ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER}}
            gcp-service-account-email: ${{secrets.BUILD_USER_EMAIL}}
            gcp-project-id: "lab-operations"
            skip-caches: "true"
            use-ssh-agent: "true"
            ssh-private-key: ${{ secrets.TG_GH_AGLABS_TF_MODULES_SSH_DEPLOY_KEY }}
            terragrunt-command: |
              terragrunt run-all apply --terragrunt-non-interactive --terragrunt-include-dir ./${{ inputs.infrastructure_path }}
          env:
            state_encryption_key: ${{ secrets.TF_STATE_ENCRYPTION_KEY}}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
            secrets:        ${{ toJson(secrets) }}